# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Flying K9 Agility
email: flyingk9agility@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Flying K9 Agility is a competition-focused agility school located in the Oklahoma City metropolitan area.
  The school was founded in 2015 by Erika Lee and Gayle McNish.
baseurl: "/flyingk9agility" # the subpath of your site, e.g. /blog
url: "http://flyingk9agility.com" # the base hostname & protocol for your site
facebook_username: flyingk9agility

# Build settings
markdown: kramdown
