# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Flying K9 Agility
email: flyingk9agility@gmail.com
description: >
  Flying K9 Agility is a competition-focused dog agility school located in the Oklahoma City metropolitan area.
  The school was founded in 2015 by Erika Lee and Gayle McNish.
#baseurl: "/flyingk9agility" # use for production
baseurl: "" # use during development
#url: "http://localhost:4000" # development
url: "http://www.flyingk9agility.com"
facebook_username: 115433682136799
author: Gayle McNish, Erika Lee

# Build settings
markdown: kramdown

github: [metadata]
kramdown:
 input: GFM
 hard_wrap: false
gems:
 - jekyll-coffeescript
 - jekyll-paginate
 - jekyll-seo-tag
